DECLARE @content NVARCHAR(MAX) = N'{"ComponentDynamics":[{"Type":3,"Id":"TuanHoan","Label":"Tuần hoàn","Value":null,"fxFlex":"50%","fxFlexSm":"50%", "maxlength":4000, "minHeight": 22, "useVoice": false, "IsLookup": false},{"Type":5,"Id":"TuanHoanPhanLoai","Label":"Phân loại","Value":null,"fxFlex":"50%","fxFlexSm":"50%", "maxlength":null, "minHeight": null, "useVoice": false, "IsLookup": true},{"Type":3,"Id":"HoHap","Label":"Hô hấp","Value":null,"fxFlex":"50%","fxFlexSm":"50%", "maxlength":4000, "minHeight": 22, "useVoice": false, "IsLookup": false},{"Type":5,"Id":"HoHapPhanLoai","Label":"Phân loại","Value":null,"fxFlex":"50%","fxFlexSm":"50%", "maxlength":null, "minHeight": null, "useVoice": false, "IsLookup": true},{"Type":3,"Id":"TieuHoa","Label":"Tiêu hóa","Value":null,"fxFlex":"50%","fxFlexSm":"50%", "maxlength":4000, "minHeight": 22, "useVoice": false, "IsLookup": false},{"Type":5,"Id":"TieuHoaPhanLoai","Label":"Phân loại","Value":null,"fxFlex":"50%","fxFlexSm":"50%", "maxlength":null, "minHeight": null, "useVoice": false, "IsLookup": true},{"Type":3,"Id":"ThanTietLieu","Label":"Thận - Tiết liệu","Value":null,"fxFlex":"50%","fxFlexSm":"50%", "maxlength":4000, "minHeight": 22, "useVoice": false, "IsLookup": false},{"Type":5,"Id":"ThanTietLieuPhanLoai","Label":"Phân loại","Value":null,"fxFlex":"50%","fxFlexSm":"50%", "maxlength":null, "minHeight": null, "useVoice": false, "IsLookup": true},{"Type":3,"Id":"NoiTiet","Label":"Nội tiết","Value":null,"fxFlex":"50%","fxFlexSm":"50%", "maxlength":4000, "minHeight": 22, "useVoice": false, "IsLookup": false},{"Type":5,"Id":"NoiTietPhanLoai","Label":"Phân loại","Value":null,"fxFlex":"50%","fxFlexSm":"50%", "maxlength":null, "minHeight": null, "useVoice": false, "IsLookup": true},{"Type":3,"Id":"CoXuongKhop","Label":"Cơ xương khớp","Value":null,"fxFlex":"50%","fxFlexSm":"50%", "maxlength":4000, "minHeight": 22, "useVoice": false, "IsLookup": false},{"Type":5,"Id":"CoXuongKhopPhanLoai","Label":"Phân loại","Value":null,"fxFlex":"50%","fxFlexSm":"50%", "maxlength":null, "minHeight": null, "useVoice": false, "IsLookup": true},{"Type":3,"Id":"ThanKinh","Label":"Thần kinh","Value":null,"fxFlex":"50%","fxFlexSm":"50%", "maxlength":4000, "minHeight": 22, "useVoice": false, "IsLookup": false},{"Type":5,"Id":"ThanKinhPhanLoai","Label":"Phân loại","Value":null,"fxFlex":"50%","fxFlexSm":"50%", "maxlength":null, "minHeight": null, "useVoice": false, "IsLookup": true},{"Type":3,"Id":"TamThan","Label":"Tâm thần","Value":null,"fxFlex":"50%","fxFlexSm":"50%", "maxlength":4000, "minHeight": 22, "useVoice": false, "IsLookup": false},{"Type":5,"Id":"TamThanPhanLoai","Label":"Phân loại","Value":null,"fxFlex":"50%","fxFlexSm":"50%", "maxlength":null, "minHeight": null, "useVoice": false, "IsLookup": true}]}'
UPDATE TemplateDichVuKhamSucKhoe
set ComponentDynamics = @content
where ChuyenKhoaKhamSucKhoe = 1

UPDATE YeuCauKhamBenh
SET ThongTinKhamTheoDichVuTemplate = @content
WHERE ChuyenKhoaKhamSucKhoe = 1 AND ThongTinKhamTheoDichVuTemplate IS NOT NULL

GO
UPDATE CauHinh
Set [Value] = '1.9.7' where [Name] = 'CauHinhHeThong.DatabaseVesion'