BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.YeuCauKhamBenhLichSuTrangThai
	DROP CONSTRAINT FK_YeuCauKhamBenhLichSuTrangThai_YeuCauKhamBenh1
GO
ALTER TABLE dbo.YeuCauKhamBenh SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.YeuCauKhamBenhLichSuTrangThai ADD CONSTRAINT
	FK_YeuCauKhamBenhLichSuTrangThai_YeuCauKhamBenh1 FOREIGN KEY
	(
	YeuCauKhamBenhId
	) REFERENCES dbo.YeuCauKhamBenh
	(
	Id
	) ON UPDATE  NO ACTION 
	 ON DELETE  CASCADE 
	
GO
ALTER TABLE dbo.YeuCauKhamBenhLichSuTrangThai SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
GO

Update dbo.CauHinh
Set [Value] = '2.2.6' where [Name] = 'CauHinhHeThong.DatabaseVesion'