CREATE TABLE [dbo].[DonThuocThanhToanChiTietTheoPhieuThu] (
    [Id]                        BIGINT          IDENTITY (1, 1) NOT NULL,
    [SoLuongToa]                FLOAT (53)      NULL,
    [BacSiKeDonId]              BIGINT          NULL,
    [ThoiDiemKeDon]             DATETIME        NULL,
    [Solo]                      NVARCHAR (50)   NOT NULL,
    [HanSuDung]                 DATETIME        NOT NULL,
    [MaVach]                    NVARCHAR (100)  NULL,
    [NgayNhapVaoBenhVien]       DATETIME        NOT NULL,
    [LoaiDonThuoc]              INT             NOT NULL,
    [NgayPhatSinh]              DATETIME        NOT NULL,
    [DuocPhamId]                BIGINT          NOT NULL,
    [Ten]                       NVARCHAR (250)  NOT NULL,
    [TenTiengAnh]               NVARCHAR (250)  NULL,
    [SoDangKy]                  NVARCHAR (100)  NOT NULL,
    [STTHoatChat]               INT             NULL,
    [NhomChiPhi]                INT             NOT NULL,
    [MaHoatChat]                NVARCHAR (20)   NOT NULL,
    [HoatChat]                  NVARCHAR (500)  NOT NULL,
    [LoaiThuocHoacHoatChat]     INT             NOT NULL,
    [NhaSanXuat]                NVARCHAR (250)  NULL,
    [NuocSanXuat]               NVARCHAR (250)  NULL,
    [DuongDungId]               BIGINT          NOT NULL,
    [HamLuong]                  NVARCHAR (500)  NULL,
    [QuyCach]                   NVARCHAR (250)  NULL,
    [TieuChuan]                 NVARCHAR (50)   NULL,
    [DangBaoChe]                NVARCHAR (250)  NULL,
    [DonViTinhId]               BIGINT          NOT NULL,
    [HuongDan]                  NVARCHAR (4000) NULL,
    [MoTa]                      NVARCHAR (4000) NULL,
    [ChiDinh]                   NVARCHAR (4000) NULL,
    [ChongChiDinh]              NVARCHAR (4000) NULL,
    [LieuLuongCachDung]         NVARCHAR (4000) NULL,
    [TacDungPhu]                NVARCHAR (4000) NULL,
    [ChuYDePhong]               NVARCHAR (4000) NULL,
    [HopDongThauDuocPhamId]     BIGINT          NULL,
    [NhaThauId]                 BIGINT          NULL,
    [SoHopDongThau]             NVARCHAR (50)   NULL,
    [SoQuyetDinhThau]           NVARCHAR (50)   NULL,
    [LoaiThau]                  INT             NULL,
    [LoaiThuocThau]             INT             NULL,
    [NhomThau]                  NVARCHAR (50)   NULL,
    [GoiThau]                   NVARCHAR (2)    NULL,
    [NamThau]                   INT             NULL,
    [Gia]                       DECIMAL (15, 2) NULL,
    [SoLuong]                   FLOAT (53)      NOT NULL,
    [SoNgayDung]                INT             NULL,
    [DungSang]                  FLOAT (53)      NULL,
    [DungTrua]                  FLOAT (53)      NULL,
    [DungChieu]                 FLOAT (53)      NULL,
    [DungToi]                   FLOAT (53)      NULL,
    [SoTienBenhNhanDaChi]       DECIMAL (15, 2) NULL,
    [DuocHuongBaoHiem]          BIT             NOT NULL,
    [BaoHiemChiTra]             BIT             NULL,
    [ThoiDiemDuyetBaoHiem]      DATETIME        NULL,
    [NhanVienDuyetBaoHiemId]    BIGINT          NULL,
    [GiaBaoHiemThanhToan]       DECIMAL (15, 2) NULL,
    [GhiChu]                    NVARCHAR (1000) NULL,
    [CreatedById]               BIGINT          NOT NULL,
    [LastUserId]                BIGINT          NOT NULL,
    [LastTime]                  DATETIME        NOT NULL,
    [CreatedOn]                 DATETIME        NOT NULL,
    [LastModified]              ROWVERSION      NOT NULL,
    [SoTienBaoHiemTuNhanChiTra] DECIMAL (15, 2) NULL,
    [SoTienMienGiam]            DECIMAL (15, 2) NULL,
    [DonGiaBaoHiem]             DECIMAL (15, 2) NULL,
    [MucHuongBaoHiem]           INT             NULL,
    [TiLeBaoHiemThanhToan]      INT             NULL,
    [DonGiaNhap]                DECIMAL (15, 2) NOT NULL,
    [TiLeTheoThapGia]           INT             NOT NULL,
    [VAT]                       INT             NOT NULL,
    [DonGiaBan]                 AS              (round((([DonGiaNhap]+([DonGiaNhap]*[TiLeTheoThapGia])/(100))+([DonGiaNhap]*[VAT])/(100))+(([DonGiaNhap]*[TiLeTheoThapGia])*[VAT])/(10000),(2))),
    [GiaBan]                    AS              (round((([DonGiaNhap]+([DonGiaNhap]*[TiLeTheoThapGia])/(100))+([DonGiaNhap]*[VAT])/(100))+(([DonGiaNhap]*[TiLeTheoThapGia])*[VAT])/(10000),(2))*CONVERT([decimal](9,2),[SoLuong])),
    [GhiChuMienGiamThem]        NVARCHAR (1000) NULL,
    CONSTRAINT [PK__DonThuocThanhToanChiTietTheoPhieuThu] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_DonThuocThanhToanChiTietTheoPhieuThu_DonViTinh] FOREIGN KEY ([DonViTinhId]) REFERENCES [dbo].[DonViTinh] ([Id]),
    CONSTRAINT [FK_DonThuocThanhToanChiTietTheoPhieuThu_DuocPham] FOREIGN KEY ([DuocPhamId]) REFERENCES [dbo].[DuocPham] ([Id]),
    CONSTRAINT [FK_DonThuocThanhToanChiTietTheoPhieuThu_DuocPham1] FOREIGN KEY ([NhanVienDuyetBaoHiemId]) REFERENCES [dbo].[DuocPham] ([Id]),
    CONSTRAINT [FK_DonThuocThanhToanChiTietTheoPhieuThu_DuongDung] FOREIGN KEY ([DuongDungId]) REFERENCES [dbo].[DuongDung] ([Id]),
    CONSTRAINT [FK_DonThuocThanhToanChiTietTheoPhieuThu_NhanVien] FOREIGN KEY ([BacSiKeDonId]) REFERENCES [dbo].[NhanVien] ([Id])
);
GO
CREATE TABLE [dbo].[DonVTYTThanhToanChiTietTheoPhieuThu] (
    [Id]                        BIGINT          IDENTITY (1, 1) NOT NULL,
    [SoLuongToa]                FLOAT (53)      NULL,
    [BacSiKeDonId]              BIGINT          NULL,
    [ThoiDiemKeDon]             DATETIME        NULL,
    [Solo]                      NVARCHAR (50)   NOT NULL,
    [HanSuDung]                 DATETIME        NOT NULL,
    [MaVach]                    NVARCHAR (100)  NULL,
    [NgayNhapVaoBenhVien]       DATETIME        NOT NULL,
    [NgayPhatSinh]              DATETIME        NOT NULL,
    [VatTuBenhVienId]           BIGINT          NOT NULL,
    [Ten]                       NVARCHAR (250)  NOT NULL,
    [Ma]                        NVARCHAR (50)   NOT NULL,
    [NhomVatTuId]               BIGINT          NOT NULL,
    [DonViTinh]                 NVARCHAR (50)   NULL,
    [NhaSanXuat]                NVARCHAR (250)  NULL,
    [NuocSanXuat]               NVARCHAR (250)  NULL,
    [QuyCach]                   NVARCHAR (250)  NULL,
    [TieuChuan]                 NVARCHAR (50)   NULL,
    [MoTa]                      NVARCHAR (4000) NULL,
    [DonGiaNhap]                DECIMAL (15, 2) NOT NULL,
    [TiLeTheoThapGia]           INT             NOT NULL,
    [VAT]                       INT             NOT NULL,
    [SoLuong]                   FLOAT (53)      NOT NULL,
    [HopDongThauVatTuId]        BIGINT          NULL,
    [NhaThauId]                 BIGINT          NULL,
    [SoHopDongThau]             NVARCHAR (50)   NULL,
    [SoQuyetDinhThau]           NVARCHAR (50)   NULL,
    [LoaiThau]                  INT             NULL,
    [NhomThau]                  NVARCHAR (50)   NULL,
    [GoiThau]                   NVARCHAR (2)    NULL,
    [NamThau]                   INT             NULL,
    [SoTienBenhNhanDaChi]       DECIMAL (15, 2) NULL,
    [GhiChu]                    NVARCHAR (1000) NULL,
    [CreatedById]               BIGINT          NOT NULL,
    [LastUserId]                BIGINT          NOT NULL,
    [LastTime]                  DATETIME        NOT NULL,
    [CreatedOn]                 DATETIME        NOT NULL,
    [LastModified]              ROWVERSION      NOT NULL,
    [SoTienBaoHiemTuNhanChiTra] DECIMAL (15, 2) NULL,
    [SoTienMienGiam]            DECIMAL (15, 2) NULL,
    [DonGiaBan]                 AS              (round((([DonGiaNhap]+([DonGiaNhap]*[TiLeTheoThapGia])/(100))+([DonGiaNhap]*[VAT])/(100))+(([DonGiaNhap]*[TiLeTheoThapGia])*[VAT])/(10000),(2))),
    [GiaBan]                    AS              (round((([DonGiaNhap]+([DonGiaNhap]*[TiLeTheoThapGia])/(100))+([DonGiaNhap]*[VAT])/(100))+(([DonGiaNhap]*[TiLeTheoThapGia])*[VAT])/(10000),(2))*CONVERT([decimal](9,2),[SoLuong])),
    [GhiChuMienGiamThem]        NVARCHAR (1000) NULL,
    CONSTRAINT [PK__DonVTYTThanhToanChiTietTheoPhieuThu] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_DonVTYTThanhToanChiTietTheoPhieuThu_NhanVien] FOREIGN KEY ([BacSiKeDonId]) REFERENCES [dbo].[NhanVien] ([Id]),
    CONSTRAINT [FK_DonVTYTThanhToanChiTietTheoPhieuThu_VatTuBenhVien] FOREIGN KEY ([VatTuBenhVienId]) REFERENCES [dbo].[VatTuBenhVien] ([Id])
);
GO

ALTER TABLE [dbo].[TaiKhoanBenhNhanChi]
	ADD 
		[DonThuocThanhToanChiTietTheoPhieuThuId]     BIGINT          NULL,
		[DonVTYTThanhToanChiTietTheoPhieuThuId]      BIGINT          NULL,
		CONSTRAINT [FK_TaiKhoanBenhNhanChi_DonThuocThanhToanChiTietTheoPhieuThu] FOREIGN KEY ([DonThuocThanhToanChiTietTheoPhieuThuId]) REFERENCES [dbo].[DonThuocThanhToanChiTietTheoPhieuThu] ([Id]),
		CONSTRAINT [FK_TaiKhoanBenhNhanChi_DonVTYTThanhToanChiTietTheoPhieuThu] FOREIGN KEY ([DonVTYTThanhToanChiTietTheoPhieuThuId]) REFERENCES [dbo].[DonVTYTThanhToanChiTietTheoPhieuThu] ([Id]);
GO

UPDATE CauHinh
Set [Value] = '1.9.6' where [Name] = 'CauHinhHeThong.DatabaseVesion'