ALTER TABLE DuocPham
ALTER COLUMN SoDangKy NVARCHAR(255) NULL
GO

ALTER TABLE NoiTruDonThuocChiTiet
ALTER COLUMN SoDangKy NVARCHAR(255) NULL
GO

ALTER TABLE DonThuocThanhToanChiTiet
ALTER COLUMN SoDangKy NVARCHAR(255) NULL
GO

ALTER TABLE DonThuocThanhToanChiTietTheoPhieuThu
ALTER COLUMN SoDangKy NVARCHAR(255) NULL
GO

ALTER TABLE NoiTruChiDinhDuocPham
ALTER COLUMN SoDangKy NVARCHAR(255) NULL
GO

ALTER TABLE YeuCauDuocPhamBenhVien
ALTER COLUMN SoDangKy NVARCHAR(255) NULL
GO

ALTER TABLE NoiTruPhieuDieuTriTuVanThuoc
ALTER COLUMN SoDangKy NVARCHAR(255) NULL
GO

ALTER TABLE YeuCauDichVuKyThuatTiemChung
ALTER COLUMN SoDangKy NVARCHAR(255) NULL
GO

ALTER TABLE TuVanThuocKhamSucKhoe
ALTER COLUMN SoDangKy NVARCHAR(255) NULL
GO

ALTER TABLE YeuCauKhamBenhDonThuocChiTiet
ALTER COLUMN SoDangKy NVARCHAR(255) NULL
GO

UPDATE CauHinh
Set [Value] = '4.0.6' where [Name] = 'CauHinhHeThong.DatabaseVesion'