DECLARE @idDV2 BIGINT = (SELECT TOP 1 Id FROM DichVuKyThuatBenhVien WHERE Ma = N'TC51'), @idDP2 BIGINT = (SELECT TOP 1 Id FROM DuocPhamBenhVien WHERE Ma = N'VACVX0002') IF (@idDV2 IS NOT NULL AND @idDP2 IS NOT NULL) BEGIN  INSERT INTO DichVuKyThuatBenhVienTiemChung(DichVuKyThuatBenhVienId, DuocPhamBenhVienId, CreatedById, LastUserId, LastTime, CreatedOn) VALUES(@idDV2, @idDP2, 1, 1, GETDATE(), GETDATE()) END
DECLARE @idDV4 BIGINT = (SELECT TOP 1 Id FROM DichVuKyThuatBenhVien WHERE Ma = N'TC53'), @idDP4 BIGINT = (SELECT TOP 1 Id FROM DuocPhamBenhVien WHERE Ma = N'MMRVX0001') IF (@idDV4 IS NOT NULL AND @idDP4 IS NOT NULL) BEGIN  INSERT INTO DichVuKyThuatBenhVienTiemChung(DichVuKyThuatBenhVienId, DuocPhamBenhVienId, CreatedById, LastUserId, LastTime, CreatedOn) VALUES(@idDV4, @idDP4, 1, 1, GETDATE(), GETDATE()) END
DECLARE @idDV7 BIGINT = (SELECT TOP 1 Id FROM DichVuKyThuatBenhVien WHERE Ma = N'TC56'), @idDP7 BIGINT = (SELECT TOP 1 Id FROM DuocPhamBenhVien WHERE Ma = N'VARVX0001') IF (@idDV7 IS NOT NULL AND @idDP7 IS NOT NULL) BEGIN  INSERT INTO DichVuKyThuatBenhVienTiemChung(DichVuKyThuatBenhVienId, DuocPhamBenhVienId, CreatedById, LastUserId, LastTime, CreatedOn) VALUES(@idDV7, @idDP7, 1, 1, GETDATE(), GETDATE()) END
DECLARE @idDV8 BIGINT = (SELECT TOP 1 Id FROM DichVuKyThuatBenhVien WHERE Ma = N'TC57'), @idDP8 BIGINT = (SELECT TOP 1 Id FROM DuocPhamBenhVien WHERE Ma = N'ROTVX0002') IF (@idDV8 IS NOT NULL AND @idDP8 IS NOT NULL) BEGIN  INSERT INTO DichVuKyThuatBenhVienTiemChung(DichVuKyThuatBenhVienId, DuocPhamBenhVienId, CreatedById, LastUserId, LastTime, CreatedOn) VALUES(@idDV8, @idDP8, 1, 1, GETDATE(), GETDATE()) END
DECLARE @idDV14 BIGINT = (SELECT TOP 1 Id FROM DichVuKyThuatBenhVien WHERE Ma = N'TC64'), @idDP14 BIGINT = (SELECT TOP 1 Id FROM DuocPhamBenhVien WHERE Ma = N'EUVVX0009') IF (@idDV14 IS NOT NULL AND @idDP14 IS NOT NULL) BEGIN  INSERT INTO DichVuKyThuatBenhVienTiemChung(DichVuKyThuatBenhVienId, DuocPhamBenhVienId, CreatedById, LastUserId, LastTime, CreatedOn) VALUES(@idDV14, @idDP14, 1, 1, GETDATE(), GETDATE()) END
DECLARE @idDV15 BIGINT = (SELECT TOP 1 Id FROM DichVuKyThuatBenhVien WHERE Ma = N'TC65'), @idDP15 BIGINT = (SELECT TOP 1 Id FROM DuocPhamBenhVien WHERE Ma = N'VACVX0004') IF (@idDV15 IS NOT NULL AND @idDP15 IS NOT NULL) BEGIN  INSERT INTO DichVuKyThuatBenhVienTiemChung(DichVuKyThuatBenhVienId, DuocPhamBenhVienId, CreatedById, LastUserId, LastTime, CreatedOn) VALUES(@idDV15, @idDP15, 1, 1, GETDATE(), GETDATE()) END
DECLARE @idDV20 BIGINT = (SELECT TOP 1 Id FROM DichVuKyThuatBenhVien WHERE Ma = N'TC70'), @idDP20 BIGINT = (SELECT TOP 1 Id FROM DuocPhamBenhVien WHERE Ma = N'BCVX0010') IF (@idDV20 IS NOT NULL AND @idDP20 IS NOT NULL) BEGIN  INSERT INTO DichVuKyThuatBenhVienTiemChung(DichVuKyThuatBenhVienId, DuocPhamBenhVienId, CreatedById, LastUserId, LastTime, CreatedOn) VALUES(@idDV20, @idDP20, 1, 1, GETDATE(), GETDATE()) END
DECLARE @idDV22 BIGINT = (SELECT TOP 1 Id FROM DichVuKyThuatBenhVien WHERE Ma = N'TC72'), @idDP22 BIGINT = (SELECT TOP 1 Id FROM DuocPhamBenhVien WHERE Ma = N'IMOVX0001') IF (@idDV22 IS NOT NULL AND @idDP22 IS NOT NULL) BEGIN  INSERT INTO DichVuKyThuatBenhVienTiemChung(DichVuKyThuatBenhVienId, DuocPhamBenhVienId, CreatedById, LastUserId, LastTime, CreatedOn) VALUES(@idDV22, @idDP22, 1, 1, GETDATE(), GETDATE()) END
DECLARE @idDV25 BIGINT = (SELECT TOP 1 Id FROM DichVuKyThuatBenhVien WHERE Ma = N'TC75'), @idDP25 BIGINT = (SELECT TOP 1 Id FROM DuocPhamBenhVien WHERE Ma = N'ROTVX0001') IF (@idDV25 IS NOT NULL AND @idDP25 IS NOT NULL) BEGIN  INSERT INTO DichVuKyThuatBenhVienTiemChung(DichVuKyThuatBenhVienId, DuocPhamBenhVienId, CreatedById, LastUserId, LastTime, CreatedOn) VALUES(@idDV25, @idDP25, 1, 1, GETDATE(), GETDATE()) END
DECLARE @idDV27 BIGINT = (SELECT TOP 1 Id FROM DichVuKyThuatBenhVien WHERE Ma = N'TC77'), @idDP27 BIGINT = (SELECT TOP 1 Id FROM DuocPhamBenhVien WHERE Ma = N'VACVX0001') IF (@idDV27 IS NOT NULL AND @idDP27 IS NOT NULL) BEGIN  INSERT INTO DichVuKyThuatBenhVienTiemChung(DichVuKyThuatBenhVienId, DuocPhamBenhVienId, CreatedById, LastUserId, LastTime, CreatedOn) VALUES(@idDV27, @idDP27, 1, 1, GETDATE(), GETDATE()) END
DECLARE @idDV28 BIGINT = (SELECT TOP 1 Id FROM DichVuKyThuatBenhVien WHERE Ma = N'TC78'), @idDP28 BIGINT = (SELECT TOP 1 Id FROM DuocPhamBenhVien WHERE Ma = N'CUMHC0001') IF (@idDV28 IS NOT NULL AND @idDP28 IS NOT NULL) BEGIN  INSERT INTO DichVuKyThuatBenhVienTiemChung(DichVuKyThuatBenhVienId, DuocPhamBenhVienId, CreatedById, LastUserId, LastTime, CreatedOn) VALUES(@idDV28, @idDP28, 1, 1, GETDATE(), GETDATE()) END


GO
Update dbo.CauHinh
Set [Value] = '2.8.2' where [Name] = 'CauHinhHeThong.DatabaseVesion'
